name: Bug Report
description: Report a bug in zwasm
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps or a .wasm/.wat file to reproduce the issue.
      placeholder: |
        1. Run `zwasm run module.wasm`
        2. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: zwasm version
      description: Output of `zwasm version`
      placeholder: "1.0.0"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - macOS ARM64 (Apple Silicon)
        - Linux x86_64
        - Linux aarch64
        - Other
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, error messages, or other relevant information.
