name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why do you need it?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? API sketch or design ideas welcome.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered and why they don't work.
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - CLI
        - Library API
        - Performance
        - Spec compliance
        - Documentation
        - Other
    validations:
      required: true
