//! End-to-end JIT tests for the `run*Export` family in `runner.zig`
//! (compile → setup → invoke via the JIT C-ABI entry → compare).
//! Extracted from `runner.zig` to keep that file under the file-size
//! hard cap as the spec-corpus JIT mode grows more `run*Export`
//! wrappers (ADR-0128 §1). Discovered by the unit-test loader via
//! `src/zwasm.zig`'s `test {}` block.
//!
//! Today's tests use hand-inlined wasm bytes — generated by
//! `xxd test/edge_cases/p7/.../<case>.wasm` on the fixtures committed
//! in sub-3c.

const std = @import("std");
const builtin = @import("builtin");
const testing = std.testing;
const Allocator = std.mem.Allocator;
const skip = @import("../test_support/skip.zig");

const runner = @import("runner.zig");
const compileWasm = runner.compileWasm;
const CompiledWasm = runner.CompiledWasm;
const findExportFunc = runner.findExportFunc;
const runI32Export = runner.runI32Export;
const runI64Export = runner.runI64Export;
const runF32Export = runner.runF32Export;
const runF64Export = runner.runF64Export;
const runVoidExport = runner.runVoidExport;
const runScalar1Export = runner.runScalar1Export;
const JitInstance = runner.JitInstance;

const entry = @import("codegen/shared/entry.zig");
const setup_mod = @import("setup.zig");
const setupRuntime = setup_mod.setupRuntime;
const TypedResult = @import("codegen/shared/entry_buffer_write.zig").TypedResult;

test "runI32Export: memory64 store+load round-trip via i64 idx_type (ADR-0111 D4 e2e)" {
    // D-181 discharge: x86_64 SysV `emitMemOpI64` X-form + wrap-check
    // body is implemented (src/engine/codegen/x86_64/op_memory.zig:306);
    // `usesRuntimePtr` already whitelists all memory load/store ops
    // (src/engine/codegen/x86_64/usage.zig:60). Ungated for Mac aarch64
    // + Linux x86_64 SysV per ADR-0111 D4. Windows skip retained
    // (phase-boundary host).
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (memory i64 1)
    //   (func (export "test") (result i32)
    //     i64.const 0    ;; address (i64-indexed memory takes i64 addr)
    //     i32.const 42   ;; value to store
    //     i32.store offset=0 align=2
    //     i64.const 0    ;; address (load)
    //     i32.load offset=0 align=2))
    //
    // End-to-end verification of the 10.M-1..10.M-4c chain:
    //   parser (memory section i64 flag) → validator (i64 addr type) →
    //   lower (MemArgExtra packed) → codegen (emitMemOpI64 X-form +
    //   wrap-check) → runtime (Runtime.memories[0] populated with
    //   idx_type=.i64). Returns 42 (stored, then loaded).
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // \0asm + version
        // type sec: 1 type, () -> i32
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f,
        // func sec: 1 func, type 0
        0x03,
        0x02, 0x01, 0x00,
        // memory sec: 1 mem, flag=0x04 (i64, min only), min=1
        0x05, 0x03, 0x01, 0x04, 0x01,
        // export sec: 1 export, name="test" (len 4), kind=func, idx=0
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74,
        0x00, 0x00,
        // code sec: 1 body, size 14
        //   0x00              locals_count = 0
        //   0x42 0x00         i64.const 0  (addr)
        //   0x41 0x2A         i32.const 42 (value)
        //   0x36 0x02 0x00    i32.store align=2 offset=0
        //   0x42 0x00         i64.const 0  (addr)
        //   0x28 0x02 0x00    i32.load align=2 offset=0
        //   0x0B              end
        0x0a, 0x10, 0x01, 0x0e, 0x00, 0x42,
        0x00, 0x41, 0x2a, 0x36, 0x02, 0x00, 0x42, 0x00,
        0x28, 0x02, 0x00, 0x0b,
    };
    const result = try runI32Export(testing.allocator, &bytes, "test");
    try testing.expectEqual(@as(u32, 42), result);
}

test "runI32Export: trunc_sat_f32_s/pos_inf returns INT32_MAX" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "test") (result i32) f32.const +inf
    //   i32.trunc_sat_f32_s)) — compiled via wat2wasm 1.0.39.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, 0x03,
        0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74,
        0x65, 0x73, 0x74, 0x00, 0x00, 0x0a, 0x0b, 0x01,
        0x09, 0x00, 0x43, 0x00, 0x00, 0x80, 0x7f, 0xfc,
        0x00, 0x0b,
    };
    const result = try runI32Export(testing.allocator, &bytes, "test");
    try testing.expectEqual(@as(u32, 2147483647), result);
}

test "runI32Export: trunc_sat_f32_s/nan returns 0" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "test") (result i32) f32.const nan
    //   i32.trunc_sat_f32_s))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, 0x03,
        0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74,
        0x65, 0x73, 0x74, 0x00, 0x00, 0x0a, 0x0b, 0x01,
        0x09, 0x00, 0x43, 0x00, 0x00, 0xc0, 0x7f, 0xfc,
        0x00, 0x0b,
    };
    const result = try runI32Export(testing.allocator, &bytes, "test");
    try testing.expectEqual(@as(u32, 0), result);
}

test "runI32Export: trunc_sat_f32_s/neg_inf returns INT32_MIN (as u32 = 0x80000000)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "test") (result i32) f32.const -inf
    //   i32.trunc_sat_f32_s))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, 0x03,
        0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74,
        0x65, 0x73, 0x74, 0x00, 0x00, 0x0a, 0x0b, 0x01,
        0x09, 0x00, 0x43, 0x00, 0x00, 0x80, 0xff, 0xfc,
        0x00, 0x0b,
    };
    const result = try runI32Export(testing.allocator, &bytes, "test");
    try testing.expectEqual(@as(u32, 0x80000000), result);
}

test "runI32Export: trunc_f32_s/nan traps (sub-7.5b-ii trap_flag detection)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "test") (result i32) f32.const nan
    //   i32.trunc_f32_s)) — Wasm 1.0 trapping trunc; NaN → trap.
    // Same module shape as the sat variant, only the opcode
    // differs: 0xa8 (i32.trunc_f32_s) instead of 0xfc 0x00.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, 0x03,
        0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74,
        0x65, 0x73, 0x74, 0x00, 0x00, 0x0a, 0x0a, 0x01,
        0x08, 0x00, 0x43, 0x00, 0x00, 0xc0, 0x7f, 0xa8,
        0x0b,
    };
    try testing.expectError(entry.Error.Trap, runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: simple i32.const probe on all hosts (sanity)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "test") (result i32) (i32.const 42)))
    // Simplest possible runI32Export fixture — verifies the basic
    // entry-shim + JIT pipeline works on the current host
    // independent of any EH machinery.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74,
        0x65, 0x73, 0x74, 0x00, 0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a,
        0x0b,
    };
    try testing.expectEqual(@as(u32, 42), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: direct return_call tail-call returns 42 end-to-end (10.TC-JIT / D-205)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (func $test (export "test") (result i32) (return_call $answer))
    //   (func $answer (result i32) (i32.const 42)))
    //
    // Exercises the full parse→validate→JIT-compile→execute pipeline
    // for `return_call` (Wasm 3.0 §3.3.8.18). The arm64 emit
    // (emit.zig .return_call → op_tail_call.emitDirectReturnCall) and
    // the B/JMP fixup are linker-tested in isolation
    // (shared/linker.zig); this is the first runI32Export-level
    // assertion that the same-module direct tail-call reaches the
    // callee body and returns its result. D-205 discharge anchor.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x09, 0x02, 0x60, 0x00, 0x01, 0x7f, 0x60, 0x00, 0x01, 0x7f, // type: 2× () -> i32
        0x03, 0x03, 0x02, 0x00, 0x01, // func: func0→type0, func1→type1
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x00, // export "test" → func0
        0x0a, 0x0b, 0x02, 0x04, 0x00, 0x12, 0x01, 0x0b, 0x04, 0x00, 0x41, 0x2a, 0x0b, // code: fn0 return_call 1; fn1 i32.const 42
    };
    try testing.expectEqual(@as(u32, 42), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: return_call_indirect through table[0] returns 99 end-to-end (10.TC-JIT / D-205)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (type $sig (func (result i32)))
    //   (table 1 funcref)
    //   (elem (i32.const 0) $worker)
    //   (func $worker (type $sig) (i32.const 99))
    //   (func $test (export "test") (result i32)
    //     (i32.const 0) (return_call_indirect (type $sig))))
    //
    // Exercises the indirect tail-call JIT path end-to-end
    // (emit.zig .return_call_indirect → op_tail_call.emitIndirectReturnCall:
    // bounds-check + sig-check + funcptr→X16 + frame_teardown + BR X16,
    // table-0/≤2-results fast path). Companion to the direct
    // return_call e2e test; both now reach the callee body after the
    // liveness terminator-class fix. Wasm spec 3.0 §3.3.8.19.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, // type: () -> i32
        0x03, 0x03, 0x02, 0x00, 0x00, // func: worker→type0, test→type0
        0x04, 0x04, 0x01, 0x70, 0x00, 0x01, // table: 1 funcref
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x01, // export "test" → func1
        0x09, 0x07, 0x01, 0x00, 0x41, 0x00, 0x0b, 0x01, 0x00, // elem: table[0] = func0 (payload 7 bytes)
        0x0a, 0x0f, 0x02, 0x05, 0x00, 0x41, 0xe3, 0x00, 0x0b, 0x07, 0x00, 0x41, 0x00, 0x13, 0x00, 0x00, 0x0b, // code: fn0 i32.const 99 (LEB 0xe3 0x00); fn1 i32.const 0; return_call_indirect type0 table0
    };
    try testing.expectEqual(@as(u32, 99), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: tail-recursive return_call with args sums to 15 (10.TC-JIT / D-205 clang_musttail shape)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (func $sum (param $n i32) (param $acc i32) (result i32)
    //     (if (i32.eqz (local.get $n)) (then (return (local.get $acc))))
    //     (return_call $sum
    //       (i32.sub (local.get $n) (i32.const 1))
    //       (i32.add (local.get $acc) (local.get $n))))
    //   (func $test (export "test") (result i32)
    //     (return_call $sum (i32.const 5) (i32.const 0))))
    //
    // The actual D-205 trigger SHAPE: direct return_call WITH non-empty
    // args + self-recursion (clang __attribute__((musttail))). IT-2/3
    // used zero args (marshalCallArgs no-op); this exercises arg
    // marshalling (X1/X2 per AAPCS64) AND frame REUSE across 6 tail-recursive
    // levels — proper tail-call must not grow the native stack.
    // sum(5,0) → 5+4+3+2+1 = 15. Wasm spec 3.0 §3.3.8.18.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x0b, 0x02, 0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f, 0x60, 0x00, 0x01, 0x7f, // type0 (i32,i32)->i32, type1 ()->i32
        0x03, 0x03, 0x02, 0x00, 0x01, // func: sum→type0, test→type1
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x01, // export "test" → func1
        0x0a, 0x22, 0x02, // code: 2 bodies, payload 0x22
        // body0 $sum (size 0x17): if(eqz n) return acc; return_call sum(n-1, acc+n)
        0x17, 0x00, 0x20,
        0x00, 0x45, 0x04,
        0x40, 0x20, 0x01,
        0x0f, 0x0b, 0x20,
        0x00, 0x41, 0x01,
        0x6b, 0x20, 0x01,
        0x20, 0x00, 0x6a,
        0x12, 0x00, 0x0b,
        // body1 $test (size 0x08): return_call sum(5, 0)
        0x08, 0x00, 0x41,
        0x05, 0x41, 0x00,
        0x12, 0x00, 0x0b,
    };
    try testing.expectEqual(@as(u32, 15), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: call_ref through a funcref returns 42 end-to-end (10.R-call_ref-JIT / D-186)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // arm64 (manual switch in emit.zig) + x86_64 (collected per-op
    // dispatch_collector_ops.zig) both emit call_ref as of 10.R-call_ref-JIT IT-2.
    // (module
    //   (type $sig (func (param i32) (result i32)))
    //   (func $double (export "double") (type $sig) local.get 0 i32.const 2 i32.mul)
    //   (func $test (export "test") (result i32)
    //     i32.const 21 (ref.func $double) (call_ref $sig)))
    //
    // First JIT call_ref: ref.func pushes @intFromPtr(&func_entities[0])
    // (a *FuncEntity, already JIT-emitted); call_ref pops it, null-checks,
    // loads the funcptr from the FuncEntity (funcentity_funcptr_offset),
    // and BLRs. $double(21) = 42. ($double exported so ref.func 0 is in
    // the ref-able set per spec.) Wasm spec 3.0 §3.3.8.13 (call_ref).
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x0a, 0x02, 0x60, 0x01, 0x7f, 0x01, 0x7f, 0x60, 0x00, 0x01, 0x7f, // type0 (i32)->i32, type1 ()->i32
        0x03, 0x03, 0x02, 0x00, 0x01, // func: double→type0, test→type1
        0x07, 0x11, 0x02, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x00, 0x00, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x01, // export "double"→f0, "test"→f1
        0x0a, 0x12, 0x02, 0x07, 0x00, 0x20, 0x00, 0x41, 0x02, 0x6c, 0x0b, 0x08, 0x00, 0x41, 0x15, 0xd2, 0x00, 0x14, 0x00, 0x0b, // code: double=local.get0*2; test=21 ref.func0 call_ref0
    };
    try testing.expectEqual(@as(u32, 42), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: return_call_ref tail-call through a funcref returns 42 (10.R / D-206)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // arm64 (manual switch in emit.zig) + x86_64 (collected per-op in
    // dispatch_collector_ops.zig) both emit return_call_ref as of cyc207.
    // (module
    //   (type $sig (func (result i32)))
    //   (func $worker (export "worker") (type $sig) (i32.const 42))
    //   (func $test (export "test") (result i32)
    //     ref.func $worker return_call_ref $sig))
    //
    // Tail-call variant of call_ref: ref.func pushes *FuncEntity;
    // return_call_ref pops it, null-checks, derefs funcentity_funcptr_offset,
    // tears down the caller frame, BRs to $worker (no return here). $worker → 42.
    // Wasm spec 3.0 §3.3.8.20.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, // type0 () -> i32
        0x03, 0x03, 0x02, 0x00, 0x00, // func: worker→type0, test→type0
        0x07, 0x11, 0x02, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x00, 0x00, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x01, // export "worker"→f0, "test"→f1
        0x0a, 0x0d, 0x02, 0x04, 0x00, 0x41, 0x2a, 0x0b, 0x06, 0x00, 0xd2, 0x00, 0x15, 0x00, 0x0b, // code: worker=i32.const42; test=ref.func0 return_call_ref0
    };
    try testing.expectEqual(@as(u32, 42), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: call_ref of a null funcref traps (10.R / D-207 null-trap)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // D-208 (discharged): the x86_64 null funcref returned 0 instead of
    // trapping because call_ref was missing from `usesRuntimePtr`, so the
    // trap stub wrote trap_flag via an uninitialised R15. Now whitelisted.
    // (module (type $sig (func (result i32)))
    //   (func $test (export "test") (result i32) ref.null $sig call_ref $sig))
    //
    // Exercises the call_ref null-check (arm64 CMP X17,#0;B.EQ — x86_64 OR r,r;JZ —
    // → shared bounds trap stub). ref.null $sig = 0xd0 + sleb heaptype 0. Wasm
    // spec §4.4.8.13: call_ref of a null reference traps.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, // type0 () -> i32
        0x03, 0x02, 0x01, 0x00, // func: test→type0
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x00, // export "test" → func0
        0x0a, 0x08, 0x01, 0x06, 0x00, 0xd0, 0x00, 0x14, 0x00, 0x0b, // code: ref.null 0; call_ref 0
    };
    try testing.expectError(entry.Error.Trap, runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: return_call_ref of a null funcref traps (10.R/10.TC / D-207 null-trap)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // D-208 (discharged): return_call_ref was missing from `usesRuntimePtr`
    // (same gap as call_ref) → x86_64 trap stub wrote trap_flag via an
    // uninitialised R15 → null funcref returned 0 instead of trapping.
    // Same as the call_ref null-trap but the tail-call variant
    // (return_call_ref = 0x15). The null-check fires before frame teardown.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // magic + version
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, // type0 () -> i32
        0x03, 0x02, 0x01, 0x00, // func: test→type0
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x00, // export "test" → func0
        0x0a, 0x08, 0x01, 0x06, 0x00, 0xd0, 0x00, 0x15, 0x00, 0x0b, // code: ref.null 0; return_call_ref 0
    };
    try testing.expectError(entry.Error.Trap, runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: throw + catch_all returns 42 (IT-6 cycle 3c-iii-d end-to-end)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (tag $e0)
    //   (func (export "test") (result i32)
    //     (block $catch
    //       (try_table (catch_all $catch)
    //         (throw $e0))
    //       (return (i32.const 99)))
    //     (i32.const 42)))
    //
    // Acceptance per Phase 10 EH integration plan §IT-6:
    //   end-to-end `throw 0` catches via `try_table catch_all 0`,
    //   lands at the catch_all block, returns normally with the
    //   "caught" sentinel 42 (not the "fallthrough" 99 and not a
    //   trap).
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x60,
        0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x01, 0x0d, 0x03,
        0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00,
        0x00, 0x0a, 0x15, 0x01, 0x13, 0x00, 0x02, 0x40, 0x1f, 0x40, 0x01, 0x02,
        0x00, 0x08, 0x00, 0x0b, 0x41, 0xe3, 0x00, 0x0f, 0x0b, 0x41, 0x2a, 0x0b,
    };
    try testing.expectEqual(@as(u32, 42), try runI32Export(testing.allocator, &bytes, "test"));

    // Companion check: same shape WITHOUT the catch_all clause →
    // throw propagates uncaught → trap (verifies the dispatch
    // pipeline distinguishes the two cases, not just that
    // landing_pad happens to land at i32.const 42 unconditionally).
    const uncaught_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x60,
        0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x01, 0x0d, 0x03,
        0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00,
        0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x08, 0x00, 0x0b,
    };
    try testing.expectError(entry.Error.Trap, runI32Export(testing.allocator, &uncaught_bytes, "test"));
}

test "runI32Export: return_call inside try_table — tail-call consumes the frame so the throw escapes the handler (10.TC × 10.E)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // EH × Tail-Call integration (ROADMAP 10.TC / 10.E `return_call_in_try_table`).
    // A `return_call` is a proper tail-call: frame_teardown consumes the caller's
    // frame — including the PC range its try_table covers — before the tail-jump.
    // So when the tail-callee throws, the throw-site PC is inside the callee
    // (outside the caller's try_table range) AND the frame-chain walk skips the
    // consumed frame. The caller's `catch_all` therefore does NOT catch the
    // tail-callee's throw; it propagates uncaught → trap. A regression (stale
    // handler entry / wrong PC normalisation) would instead catch it → 42.
    //
    // wat2wasm --enable-tail-call --enable-exceptions:
    //   (module
    //     (tag $e0)
    //     (func $thrower (result i32) (throw $e0))
    //     (func (export "test") (result i32)
    //       (block $catch
    //         (try_table (catch_all $catch)
    //           (return_call $thrower))   ;; tail-call; the caller's frame is gone
    //         (return (i32.const 99)))
    //       (i32.const 42)))              ;; $catch landing pad — never reached
    const escapes_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x60,
        0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x03, 0x02, 0x01, 0x01, 0x0d,
        0x03, 0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74,
        0x00, 0x01, 0x0a, 0x1a, 0x02, 0x04, 0x00, 0x08, 0x00, 0x0b, 0x13, 0x00,
        0x02, 0x40, 0x1f, 0x40, 0x01, 0x02, 0x00, 0x12, 0x00, 0x0b, 0x41, 0xe3,
        0x00, 0x0f, 0x0b, 0x41, 0x2a, 0x0b,
    };
    try testing.expectError(entry.Error.Trap, runI32Export(testing.allocator, &escapes_bytes, "test"));

    // Companion: a NON-throwing tail-call inside the same try_table shape just
    // returns the tail-callee's result (77) — the try_table setup doesn't break
    // the tail-call disposition.
    //   (module
    //     (func $non_throw (result i32) (i32.const 77))
    //     (func (export "test") (result i32)
    //       (block $catch
    //         (try_table (catch_all $catch)
    //           (return_call $non_throw)))
    //       (i32.const 0)))
    const non_throw_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x03, 0x03, 0x02, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04,
        0x74, 0x65, 0x73, 0x74, 0x00, 0x01, 0x0a, 0x17, 0x02, 0x05, 0x00, 0x41,
        0xcd, 0x00, 0x0b, 0x0f, 0x00, 0x02, 0x40, 0x1f, 0x40, 0x01, 0x02, 0x00,
        0x12, 0x00, 0x0b, 0x0b, 0x41, 0x00, 0x0b,
    };
    try testing.expectEqual(@as(u32, 77), try runI32Export(testing.allocator, &non_throw_bytes, "test"));
}

test "runI32Export: tagged catch routes by tag_idx — throw $e1 → catch $e1 returns 77" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (tag $e0) (tag $e1)
    //   (func (export "test") (result i32)
    //     (block $catch_e1
    //       (block $catch_e0
    //         (try_table (catch $e0 $catch_e0) (catch $e1 $catch_e1)
    //           (throw $e1))
    //         unreachable)
    //       unreachable)
    //     (i32.const 77)))
    //
    // Exercises op_throw's tag_idx marshal: throws tag 1; the
    // unwinder must match the SECOND HandlerEntry (catch $e1 → 1),
    // NOT the first (catch $e0 → 0). Without the marshal, the
    // throw site delivers garbage `tag_idx`, and the dispatcher's
    // match would be undefined — likely hitting catch_e0 (= trap
    // via unreachable between $catch_e0 and $catch_e1) or
    // mis-matching entirely. With the marshal, tag 1 hits the
    // SECOND entry → branch to $catch_e1 → fall through to
    // `(i32.const 77)` → return 77.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x60,
        0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x01, 0x0d, 0x05,
        0x02, 0x00, 0x00, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73,
        0x74, 0x00, 0x00, 0x0a, 0x1b, 0x01, 0x19, 0x00, 0x02, 0x40, 0x02, 0x40,
        0x1f, 0x40, 0x02, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x08, 0x01, 0x0b,
        0x00, 0x0b, 0x00, 0x0b, 0x41, 0xcd, 0x00, 0x0b,
    };
    try testing.expectEqual(@as(u32, 77), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: cross-frame throw — callee throws, caller's try_table catches (D-183)" {
    // D-184 closed — x86_64 prologue-aware sniffed loadFrame in
    // frame_chain.loadFrameSniffed disambiguates the saved-RBP
    // vs saved-R15 slot via CodeMap lookup. Test ungated for
    // Mac aarch64 + Linux x86_64 SysV; windows = phase-boundary
    // gate per ADR-0067.
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (tag $e0)
    //   (func $callee (throw $e0))
    //   (func (export "test") (result i32)
    //     (block $catch
    //       (try_table (catch_all $catch)
    //         call $callee)
    //       (return (i32.const 99)))
    //     (i32.const 42)))
    //
    // D-183 discharge: the dispatcher's initial_pc + the
    // unwinder's caller_pc are now both module-relative (=
    // `absolute_pc - block_addr`), matching the module-relative
    // pc_start/pc_end stored by `collectModuleTable`. Prior to
    // the fix, dispatch returned function-relative PCs which
    // happened to equal module-relative only for the first
    // defined function — multi-function modules fell through to
    // `.uncaught` because the caller's pc range was offset by
    // the preceding function(s)'s byte length.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x60,
        0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x03, 0x02, 0x00, 0x01, 0x0d,
        0x03, 0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74,
        0x00, 0x01, 0x0a, 0x1a, 0x02, 0x04, 0x00, 0x08, 0x00, 0x0b, 0x13, 0x00,
        0x02, 0x40, 0x1f, 0x40, 0x01, 0x02, 0x00, 0x10, 0x00, 0x0b, 0x41, 0xe3,
        0x00, 0x0f, 0x0b, 0x41, 0x2a, 0x0b,
    };
    try testing.expectEqual(@as(u32, 42), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: multi-catch try_table — tag-correct clause's prelude pushes payload (D-182 per-clause)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (type $t (func (param i32)))
    //   (tag $e0 (type $t))
    //   (tag $e1 (type $t))
    //   (func (export "test") (result i32)
    //     (block $catch (result i32)
    //       (try_table (catch $e0 $catch) (catch $e1 $catch)
    //         i32.const 88
    //         throw $e1)
    //       i32.const 99)))
    //
    // Exercises the per-clause prelude path in D-182's
    // landing_pad_fixups patch site: BOTH catches target the
    // same outer label ($catch) and BOTH have N=1 payload
    // counts, so each clause needs its own prelude emitting
    // a load-from-eh_payload_buf into the block-result vreg.
    // The dispatcher's `entry.tag_idx` lookup picks catch $e1
    // → its prelude fires → pushes 88 → block returns 88.
    //
    // If the per-clause-prelude path were broken (e.g.,
    // matching both fixups to the same landing_pad_pc),
    // the dispatcher could land at the wrong clause and
    // the regression would surface as 0 or 99.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x09, 0x02, 0x60,
        0x01, 0x7f, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x01, 0x0d,
        0x05, 0x02, 0x00, 0x00, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65,
        0x73, 0x74, 0x00, 0x00, 0x0a, 0x19, 0x01, 0x17, 0x00, 0x02, 0x7f, 0x1f,
        0x40, 0x02, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x41, 0xd8, 0x00, 0x08,
        0x01, 0x0b, 0x41, 0xe3, 0x00, 0x0b, 0x0b,
    };
    try testing.expectEqual(@as(u32, 88), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: cross-frame throw with i32 payload — propagates via eh_payload_buf across frames" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (type $t0 (func (param i32)))
    //   (tag $e0 (type $t0))
    //   (func $callee
    //     i32.const 55
    //     throw $e0)
    //   (func (export "test") (result i32)
    //     (block $catch (result i32)
    //       (try_table (catch $e0 $catch)
    //         call $callee)
    //       i32.const 99)))
    //
    // Validates that `eh_payload_buf` (per-Runtime, NOT
    // stack-allocated) survives the cross-frame FP-walk. callee
    // throws with payload 55; the buffer is written at the
    // throw site (in callee). The walker traverses to test's
    // frame, matches catch_$e0, loads the payload from the same
    // buffer (still 55 — no other writes intervened), pushes
    // 55 into the block-result vreg. Returns 55.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x0c, 0x03, 0x60,
        0x01, 0x7f, 0x00, 0x60, 0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x03,
        0x02, 0x01, 0x02, 0x0d, 0x03, 0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04,
        0x74, 0x65, 0x73, 0x74, 0x00, 0x01, 0x0a, 0x1a, 0x02, 0x06, 0x00, 0x41,
        0x37, 0x08, 0x00, 0x0b, 0x11, 0x00, 0x02, 0x7f, 0x1f, 0x40, 0x01, 0x00,
        0x00, 0x00, 0x10, 0x00, 0x0b, 0x41, 0xe3, 0x00, 0x0b, 0x0b,
    };
    try testing.expectEqual(@as(u32, 55), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: 2-level cross-frame throw — inner→mid→test catches via outermost try_table" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (tag $e0)
    //   (func $inner (throw $e0))
    //   (func $mid (call $inner))
    //   (func (export "test") (result i32)
    //     (block $catch
    //       (try_table (catch_all $catch)
    //         call $mid)
    //       (return (i32.const 99)))
    //     (i32.const 77)))
    //
    // Exercises the FP-walk unwinder traversing 2 frames
    // (inner → mid → test). Verifies the sniffed loadFrame
    // (D-184) handles repeated walk-step disambiguation —
    // each frame has uses_runtime_ptr=true (every function
    // either throws, calls, or has try_table), so each frame's
    // [RBP, 0] holds saved R15 (rt ptr value), not saved RBP.
    // The CodeMap-aware sniff per frame finds the correct
    // saved-RBP slot each iteration.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x60,
        0x00, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x04, 0x03, 0x00, 0x00, 0x01,
        0x0d, 0x03, 0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73,
        0x74, 0x00, 0x02, 0x0a, 0x20, 0x03, 0x04, 0x00, 0x08, 0x00, 0x0b, 0x04,
        0x00, 0x10, 0x00, 0x0b, 0x14, 0x00, 0x02, 0x40, 0x1f, 0x40, 0x01, 0x02,
        0x00, 0x10, 0x01, 0x0b, 0x41, 0xe3, 0x00, 0x0f, 0x0b, 0x41, 0xcd, 0x00,
        0x0b,
    };
    try testing.expectEqual(@as(u32, 77), try runI32Export(testing.allocator, &bytes, "test"));
}

test "runI32Export: throw + catch_ with i32 payload returns 88 (10.E-payload-prop bundle close)" {
    // D-182 discharge — bundle 10.E-payload-prop closed on both
    // arches. Throw side: throw.emit pops N values + stores at
    // eh_payload_buf. Catch side: emit.zig (arm64 + x86_64) at
    // the catch-label end-op-patch site emits per-clause prelude
    // loading eh_payload_buf[i] into the block-result vreg slot
    // (via gprDefSpilled + gprStoreSpilled) + JMP-to-common
    // continuation. windowsmini = phase-boundary per ADR-0067.
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module
    //   (type $t0 (func (param i32)))
    //   (tag $e0 (type $t0))
    //   (func (export "test") (result i32)
    //     (block $catch (result i32)
    //       (try_table (catch $e0 $catch)
    //         i32.const 88
    //         throw $e0
    //       )
    //       i32.const 99
    //     )))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x09, 0x02, 0x60,
        0x01, 0x7f, 0x00, 0x60, 0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x01, 0x0d,
        0x03, 0x01, 0x00, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74,
        0x00, 0x00, 0x0a, 0x16, 0x01, 0x14, 0x00, 0x02, 0x7f, 0x1f, 0x40, 0x01,
        0x00, 0x00, 0x00, 0x41, 0xd8, 0x00, 0x08, 0x00, 0x0b, 0x41, 0xe3, 0x00,
        0x0b, 0x0b,
    };
    try testing.expectEqual(@as(u32, 88), try runI32Export(testing.allocator, &bytes, "test"));
}

test "compileWasm: empty module (header only) compiles to empty CompiledWasm" {
    // §9.9 / 9.9-l-1b-d093-d69: ungated (was Mac-only) so the
    // testing.allocator (DebugAllocator) leak gate runs on all
    // hosts. D-135 documents 4 leak sites traced to compileWasm's
    // empty-fn-section path on OrbStack Linux x86_64 under the
    // runCorpus `.assert_invalid` arm; this Mac-host test passes,
    // so the leak class (if real) is either Linux x86_64-specific
    // or runCorpus-lifecycle-specific (not reproducible via a
    // single compileWasm + deinit cycle).
    const bytes = [_]u8{ 0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00 };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);
    try testing.expectEqual(@as(usize, 0), compiled.func_sigs.len);
    try testing.expectEqual(@as(usize, 0), compiled.func_results.len);
}

test "compileWasm: empty function section (count=0) — binary.60.wasm shape (D-135 path)" {
    // §9.9 / 9.9-l-1b-d093-d69 (D-135 path discriminator): a
    // function section that is present-but-empty (body = single
    // LEB128 0x00 byte → count=0). This is the wasm shape D-127
    // (d-52) added explicit handling for. Per the empty-fn
    // early-return at runner.zig:138-194, this path converges
    // with the bare-header path into the `func_section_opt ==
    // null` branch — same allocations, same deinit. If this test
    // is leak-clean under testing.allocator on Mac aarch64, the
    // D-135 leak is NOT a structural deinit bug but something
    // specific to the runCorpus lifecycle (e.g. the
    // assert_invalid arm's `var c = compiled_ok; c.deinit(gpa)`
    // pattern) OR Linux x86_64-specific.
    //
    // Module bytes (binary.60.wasm exact): magic + version +
    // section 03 (function) of size 1 with body=[0x00] (count=0).
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x03, 0x01, 0x00,
    };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);
    try testing.expectEqual(@as(usize, 0), compiled.func_sigs.len);
    try testing.expectEqual(@as(usize, 0), compiled.func_results.len);
}

test "compileWasm: empty code section (count=0) — binary.61.wasm shape (D-135 path)" {
    // §9.9 / 9.9-l-1b-d093-d69 (D-135 path discriminator):
    // mirror of the binary.60 test but with the empty body in
    // the CODE section instead of the function section. binary.61
    // declares code section size=1 body=[0x00] but no function
    // section. compileWasm's `module.find(.function) == null`
    // branch fires directly (no need for the d-52 empty-body
    // check). Same downstream allocations + deinit.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x0a, 0x01, 0x00,
    };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);
    try testing.expectEqual(@as(usize, 0), compiled.func_sigs.len);
    try testing.expectEqual(@as(usize, 0), compiled.func_results.len);
}

test "compileWasm: tag_param_counts populated from tag section + types (10.E-N-3)" {
    // type(1): [(i32) -> ()]  — typeidx=0 has 1 param.
    // tag(13): [tag attr=0 typeidx=0]  — tag 0 references typeidx 0.
    // Expected: compiled.tag_param_counts = [1].
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        // type section: count=1; functype: 0x60, params=[i32], results=[]
        0x01, 0x05, 0x01, 0x60, 0x01, 0x7F, 0x00,
        // tag section (id 13): count=1; tag: attr=0x00, typeidx=0
        0x0D,
        0x03, 0x01, 0x00, 0x00,
    };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);

    try testing.expectEqual(@as(usize, 1), compiled.tag_param_counts.len);
    try testing.expectEqual(@as(u32, 1), compiled.tag_param_counts[0]);
}

test "compileWasm: tag_param_counts empty when no tag section (10.E-N-3)" {
    const bytes = [_]u8{ 0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00 };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);
    try testing.expectEqual(@as(usize, 0), compiled.tag_param_counts.len);
}

test "compileWasm: catchless try_table JIT-compiles (10.E try_table.1 try-with-param)" {
    // A try_table with zero catch clauses is valid — it's a block that
    // catches nothing (e.g. try_table.1's `try-with-param`:
    // `(i32.const 0) (try_table (param i32) (drop))`). The lowerer
    // appends a LandingPad per try_table but no catch entries, so
    // ZirFunc.eh_catch_entries stays null when ALL of a func's
    // try_tables are catchless → the emit's `eh_catch_entries orelse
    // return UnsupportedOp` wrongly rejected the whole module. The
    // catch loop over an empty [catches_start, catches_end) range is a
    // no-op; null must coerce to an empty slice, not a hard reject.
    //
    // func 0: () -> () body = `try_table (empty blocktype) <0 catches> end; end`
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        // type section (1): count=1; type0 ()->()
        0x01, 0x04, 0x01, 0x60, 0x00, 0x00,
        // function section (3): count=1; func0 -> type0
        0x03, 0x02,
        0x01, 0x00,
        // code section (10): count=1; body size=6:
        //   local-decl count=0; try_table(0x1f) blocktype=0x40 catch-count=0x00;
        //   end(0x0b) [closes try_table]; end(0x0b) [closes func]
        0x0A, 0x08, 0x01, 0x06, 0x00, 0x1F,
        0x40, 0x00, 0x0B, 0x0B,
    };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);
    try testing.expectEqual(@as(usize, 1), compiled.func_results.len);
}

test "compileWasm: multiple tags with mixed-arity types (10.E-N-3)" {
    // type 0: () -> ()         (0 params)
    // type 1: (i32 i64) -> ()  (2 params)
    // tag 0 → type 0; tag 1 → type 1; tag 2 → type 0.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        // type section: count=2
        0x01, 0x09, 0x02,
        0x60, 0x00, 0x00, // type 0: 0 params, 0 results
        0x60, 0x02, 0x7F, 0x7E, 0x00, // type 1: i32+i64 params, 0 results
        // tag section: count=3; (0,0), (0,1), (0,0)
        0x0D, 0x07, 0x03, 0x00, 0x00,
        0x00, 0x01, 0x00, 0x00,
    };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);

    try testing.expectEqual(@as(usize, 3), compiled.tag_param_counts.len);
    try testing.expectEqual(@as(u32, 0), compiled.tag_param_counts[0]);
    try testing.expectEqual(@as(u32, 2), compiled.tag_param_counts[1]);
    try testing.expectEqual(@as(u32, 0), compiled.tag_param_counts[2]);
}

test "compileWasm: tag index space includes imported tags (imports-first) — 10.E try_table.1" {
    // Regression for the JIT try_table StackTypeMismatch (exception-handling/
    // try_table.1.wasm rejects on JIT, runs on interp): the wasm tag index
    // space is imported-tags ++ defined-tags (Wasm 3.0 §3.4). The JIT compile
    // path built `tags_slice` / tag_param_counts from the DEFINED tag section
    // only, so catch/throw `tag_idx` (encoded in the full space) mis-resolved
    // by the imported-tag count → wrong tag's params → StackTypeMismatch at
    // validate, and wrong pop-count at throw. The interp already builds the
    // full space (instantiate.zig cyc114/cyc116). Mirror it here.
    //
    // type 0: () -> ()    (0 params; the imported tag's type)
    // type 1: (i32) -> () (1 param;  the defined tag's type)
    // import: tag "t"."e" → type 0  → full-space tag index 0
    // tag section: one defined tag → type 1 → full-space tag index 1
    // Expected tag_param_counts = [0, 1] (imports-first), len 2.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        // type section (1): count=2; type0 ()->(); type1 (i32)->()
        0x01, 0x08, 0x02, 0x60, 0x00, 0x00, 0x60, 0x01,
        0x7F, 0x00,
        // import section (2): count=1; "t"."e" tag attr=0 typeidx=0
        0x02, 0x08, 0x01, 0x01, 0x74, 0x01,
        0x65, 0x04, 0x00, 0x00,
        // tag section (13): count=1; defined tag attr=0 typeidx=1
        0x0D, 0x03, 0x01, 0x00,
        0x01,
    };
    var compiled = try compileWasm(testing.allocator, &bytes);
    defer compiled.deinit(testing.allocator);

    try testing.expectEqual(@as(usize, 2), compiled.tag_param_counts.len);
    try testing.expectEqual(@as(u32, 0), compiled.tag_param_counts[0]); // imported tag → type 0
    try testing.expectEqual(@as(u32, 1), compiled.tag_param_counts[1]); // defined tag → type 1
}

// ADR-0066 cross-module bridge thunk + ADR-0112 D4 (cross-module
// tail-call). Self-contained two-module JIT harness used by the
// D-206 bundle. It mirrors `resolveCrossModuleImports`
// (test/spec/spec_assert_runner_base.zig) but with the minimal
// wiring needed to JIT-execute a single cross-module call in a
// unit test: compile both instances, emit one bridge thunk into a
// JIT arena targeting the exporter's entry, plant it into the
// importer's `host_dispatch_base[0]` view (= `RuntimeOwned.dispatch`,
// per setup.zig:510), then invoke the importer's `test` export.
//
// `link` returns the live state the caller must keep alive across the
// invoke (both instances + the thunk arena) and the importer's func
// index for `test`. Result is read via `entry.callI32NoArgs`.
const CrossModuleHarness = struct {
    a_compiled: CompiledWasm,
    a_owned: setup_mod.RuntimeOwned,
    b_compiled: CompiledWasm,
    b_owned: setup_mod.RuntimeOwned,
    arena: @import("../platform/jit_mem.zig").JitBlock,
    a_test_idx: u32,

    const shared_thunk = @import("codegen/shared/thunk.zig");

    /// Wire importer `a_bytes` (one func import resolving to exporter
    /// `b_bytes`'s `b_export`) and return the harness. Caller owns
    /// `deinit`.
    fn link(
        gpa: Allocator,
        a_bytes: []const u8,
        b_bytes: []const u8,
        b_export: []const u8,
    ) !CrossModuleHarness {
        var b_compiled = try compileWasm(gpa, b_bytes);
        errdefer b_compiled.deinit(gpa);
        var b_owned = try setupRuntime(gpa, &b_compiled, b_bytes);
        errdefer b_owned.deinit(gpa);

        var a_compiled = try compileWasm(gpa, a_bytes);
        errdefer a_compiled.deinit(gpa);
        var a_owned = try setupRuntime(gpa, &a_compiled, a_bytes);
        errdefer a_owned.deinit(gpa);

        const b_idx = try findExportFunc(gpa, b_bytes, b_export);
        const callee_entry = b_compiled.module.entryAddr(b_idx);
        const callee_rt = @intFromPtr(&b_owned.rt);

        // `allocArena` flips this thread to writable (Mac W^X is
        // per-thread, so it also makes the freshly-compiled A/B
        // blocks non-executable until `finalizeArena` flips back —
        // safe because nothing runs in between). Mirrors the
        // setWritable/emit/setExecutable order in
        // `resolveCrossModuleImports`.
        const arena = try shared_thunk.allocArena(1);
        errdefer shared_thunk.freeArena(arena);
        const slot = shared_thunk.thunkSlot(arena, 0);
        shared_thunk.emitThunk(slot, callee_rt, callee_entry);
        try shared_thunk.finalizeArena(arena);
        a_owned.dispatch[0] = @intFromPtr(slot.ptr);

        const a_test_idx = try findExportFunc(gpa, a_bytes, "test");
        return .{
            .a_compiled = a_compiled,
            .a_owned = a_owned,
            .b_compiled = b_compiled,
            .b_owned = b_owned,
            .arena = arena,
            .a_test_idx = a_test_idx,
        };
    }

    fn callTest(self: *CrossModuleHarness) !u32 {
        return entry.callI32NoArgs(self.a_compiled.module, self.a_test_idx, &self.a_owned.rt);
    }

    fn deinit(self: *CrossModuleHarness, gpa: Allocator) void {
        shared_thunk.freeArena(self.arena);
        self.a_owned.deinit(gpa);
        self.a_compiled.deinit(gpa);
        self.b_owned.deinit(gpa);
        self.b_compiled.deinit(gpa);
    }
};

test "cross-module JIT CALL: A.test calls imported B.get → 42 (D-206 harness baseline)" {
    const gpa = testing.allocator;
    // wat2wasm:  (module (func (export "get") (result i32) i32.const 42))
    const b_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x07, 0x01, 0x03, 0x67,
        0x65, 0x74, 0x00, 0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a, 0x0b,
    };
    // wat2wasm:  (module (import "b" "get" (func $get (result i32)))
    //                    (func (export "test") (result i32) call $get))
    const a_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x02, 0x09, 0x01, 0x01, 0x62, 0x03, 0x67, 0x65, 0x74,
        0x00, 0x00, 0x03, 0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65,
        0x73, 0x74, 0x00, 0x01, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x10, 0x00, 0x0b,
    };

    var h = try CrossModuleHarness.link(gpa, &a_bytes, &b_bytes, "get");
    defer h.deinit(gpa);
    try testing.expectEqual(@as(u32, 42), try h.callTest());
}

// D-225 — the same cross-module CALL, but wired through the PUBLIC
// `initLinked` + `exportedFuncTarget` path (the spec runner uses this):
// the importer's setup resolves the func-import target + emits the bridge
// thunk into dispatch[0] itself, rather than the test planting it manually.
test "JitInstance.initLinked: cross-module FUNC import dispatches to exporter (D-225)" {
    const gpa = testing.allocator;
    // (module (func (export "get") (result i32) i32.const 42))
    const b_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x07, 0x01, 0x03, 0x67,
        0x65, 0x74, 0x00, 0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a, 0x0b,
    };
    // (module (import "b" "get" (func $get (result i32)))
    //         (func (export "test") (result i32) call $get))
    const a_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x02, 0x09, 0x01, 0x01, 0x62, 0x03, 0x67, 0x65, 0x74,
        0x00, 0x00, 0x03, 0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65,
        0x73, 0x74, 0x00, 0x01, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x10, 0x00, 0x0b,
    };
    // Exporter kept alive (its rt address is baked into the importer thunk).
    var b_inst = try JitInstance.init(gpa, &b_bytes);
    defer b_inst.deinit(gpa);
    const target = b_inst.exportedFuncTarget(gpa, "get") orelse return error.TestUnexpectedResult;
    var a_inst = try JitInstance.initLinked(gpa, &a_bytes, &.{}, &.{target});
    defer a_inst.deinit(gpa);
    try testing.expectEqual(@as(?u64, 42), try a_inst.invoke(gpa, "test", &.{}));
}

test "cross-module JIT return_call: A.test return_call's imported B.get → 42 (D-206 step 2)" {
    const gpa = testing.allocator;
    // Same B as the baseline test.
    const b_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x07, 0x01, 0x03, 0x67,
        0x65, 0x74, 0x00, 0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a, 0x0b,
    };
    // wat2wasm --enable-tail-call:
    //   (module (import "b" "get" (func $get (result i32)))
    //           (func (export "test") (result i32) return_call $get))
    // Identical to the baseline A except the body op is `return_call`
    // (0x12) where the baseline has `call` (0x10).
    const a_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x02, 0x09, 0x01, 0x01, 0x62, 0x03, 0x67, 0x65, 0x74,
        0x00, 0x00, 0x03, 0x02, 0x01, 0x00, 0x07, 0x08, 0x01, 0x04, 0x74, 0x65,
        0x73, 0x74, 0x00, 0x01, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x12, 0x00, 0x0b,
    };

    var h = try CrossModuleHarness.link(gpa, &a_bytes, &b_bytes, "get");
    defer h.deinit(gpa);
    try testing.expectEqual(@as(u32, 42), try h.callTest());
}

// Regression guard for the cross-module tail-call cohort invariant
// (ADR-0112 Amendment 2026-05-30 / D-206 step 2). A's `$mid` does
// `return_call $get` (cross-module tail-call); `test` calls `$mid`,
// drops the result, then `i32.load`s A's own memory[0] = 99. The load
// reads A's pinned cohort (mem base / limit). If the cross-module
// tail-call had used a frame-consuming BR-bridge it would leave B's
// cohort installed (B has no memory) → the load traps. Passing at 99
// proves the call-and-return lowering preserved A's cohort through the
// tail-call back to the same-module grand-caller. See lesson
// `2026-05-30-cross-module-tail-call-cohort-asymmetry.md`.
test "cross-module JIT return_call: same-module grand-caller's cohort survives → mem[0]=99 (D-206 step 2)" {
    const gpa = testing.allocator;
    const b_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x07, 0x01, 0x03, 0x67,
        0x65, 0x74, 0x00, 0x00, 0x0a, 0x06, 0x01, 0x04, 0x00, 0x41, 0x2a, 0x0b,
    };
    // wat2wasm --enable-tail-call:
    //   (module
    //     (import "b" "get" (func $get (result i32)))
    //     (memory 1)
    //     (data (i32.const 0) "\63\00\00\00")          ;; mem[0] = 99
    //     (func $mid (result i32) return_call $get)
    //     (func (export "test") (result i32)
    //       call $mid drop i32.const 0 i32.load))
    const a_bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x01, 0x60,
        0x00, 0x01, 0x7f, 0x02, 0x09, 0x01, 0x01, 0x62, 0x03, 0x67, 0x65, 0x74,
        0x00, 0x00, 0x03, 0x03, 0x02, 0x00, 0x00, 0x05, 0x03, 0x01, 0x00, 0x01,
        0x07, 0x08, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x00, 0x02, 0x0a, 0x11,
        0x02, 0x04, 0x00, 0x12, 0x00, 0x0b, 0x0a, 0x00, 0x10, 0x01, 0x1a, 0x41,
        0x00, 0x28, 0x02, 0x00, 0x0b, 0x0b, 0x0a, 0x01, 0x00, 0x41, 0x00, 0x0b,
        0x04, 0x63, 0x00, 0x00, 0x00,
    };

    var h = try CrossModuleHarness.link(gpa, &a_bytes, &b_bytes, "get");
    defer h.deinit(gpa);
    try testing.expectEqual(@as(u32, 99), try h.callTest());
}

// ── ADR-0128 §1 single-arg dispatch (runScalar1Export, 4×4 scalar matrix) ──

test "runScalar1Export: (i32)->i32 identity returns the arg (8ac key=0)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "id") (param i32) (result i32) local.get 0))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7f, 0x01, 0x7f, // type (i32)->(i32)
        0x03, 0x02, 0x01, 0x00, // func 0 : type 0
        0x07, 0x06, 0x01, 0x02, 0x69, 0x64, 0x00, 0x00, // export "id" func 0
        0x0a, 0x06, 0x01, 0x04, 0x00, 0x20, 0x00, 0x0b, // code: local.get 0
    };
    const got = try runScalar1Export(testing.allocator, &bytes, "id", 7);
    try testing.expectEqual(@as(u32, 7), @as(u32, @truncate(got)));
}

test "runScalar1Export: (i32)->i64 extend_u widens the arg (key=4)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (param i32)(result i64) local.get 0 i64.extend_i32_u
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7f, 0x01, 0x7e, // (i32)->(i64)
        0x03, 0x02, 0x01, 0x00, 0x07, 0x06, 0x01, 0x02,
        0x69, 0x64, 0x00, 0x00,
        0x0a, 0x07, 0x01, 0x05, 0x00, 0x20, 0x00, 0xad, 0x0b, // local.get 0; i64.extend_i32_u
    };
    const got = try runScalar1Export(testing.allocator, &bytes, "id", 5);
    try testing.expectEqual(@as(u64, 5), got);
}

test "runScalar1Export: (f32)->f32 identity round-trips the bit pattern (key=10, FP arg bank)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (param f32)(result f32) local.get 0
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7d, 0x01, 0x7d, // (f32)->(f32)
        0x03, 0x02, 0x01, 0x00, 0x07, 0x06, 0x01, 0x02,
        0x69, 0x64, 0x00, 0x00, 0x0a, 0x06, 0x01, 0x04,
        0x00, 0x20, 0x00, 0x0b,
    };
    const x: f32 = 3.5;
    const arg_bits: u64 = @as(u32, @bitCast(x));
    const got = try runScalar1Export(testing.allocator, &bytes, "id", arg_bits);
    try testing.expectEqual(@as(u32, @bitCast(x)), @as(u32, @truncate(got)));
}

test "runScalar1Export: (f64)->i32 trunc_s truncates the arg (key=12, FP arg → int result)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (param f64)(result i32) local.get 0 i32.trunc_f64_s
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7c, 0x01, 0x7f, // (f64)->(i32)
        0x03, 0x02, 0x01, 0x00, 0x07, 0x06, 0x01, 0x02,
        0x69, 0x64, 0x00, 0x00,
        0x0a, 0x07, 0x01, 0x05, 0x00, 0x20, 0x00, 0xaa, 0x0b, // local.get 0; i32.trunc_f64_s
    };
    const x: f64 = 42.0;
    const arg_bits: u64 = @bitCast(x);
    const got = try runScalar1Export(testing.allocator, &bytes, "id", arg_bits);
    try testing.expectEqual(@as(u32, 42), @as(u32, @truncate(got)));
}

// ── ADR-0128 §1 / D-214: persistent per-module JIT runtime (state accumulates) ──

test "JitInstance: global-counter bump persists state across invokes (1,2,3)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (global $g (mut i32) i32.const 0)
    //   (func (export "bump") (result i32)
    //     global.get 0  i32.const 1  i32.add  global.set 0  global.get 0))
    // Fresh-recompile-per-call would return 1 every time; a PERSISTED
    // runtime returns 1, 2, 3 — the D-214 state-accumulation contract.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, // type () -> i32
        0x03, 0x02, 0x01, 0x00, // func 0 : type 0
        0x06, 0x06, 0x01, 0x7f, 0x01, 0x41, 0x00, 0x0b, // global mut i32 = 0
        0x07, 0x08, 0x01, 0x04, 0x62, 0x75, 0x6d, 0x70, 0x00, 0x00, // export "bump" func 0
        0x0a, 0x0d, 0x01, 0x0b, 0x00, 0x23, 0x00, 0x41, 0x01, 0x6a,
        0x24, 0x00, 0x23, 0x00, 0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 1), try inst.invoke(testing.allocator, "bump", &.{}));
    try testing.expectEqual(@as(?u64, 2), try inst.invoke(testing.allocator, "bump", &.{}));
    try testing.expectEqual(@as(?u64, 3), try inst.invoke(testing.allocator, "bump", &.{}));
}

test "JitInstance: void-result invoke runs (returns null) and a 1-arg scalar invoke dispatches" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (global $g (mut i32) i32.const 0)
    //   (func (export "set") (param i32) local.get 0 global.set 0)   ;; void, 1 arg
    //   (func (export "get") (result i32) global.get 0))             ;; i32, 0 arg
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        // type sec: 2 types — t0 (i32)->() , t1 ()->(i32)
        0x01, 0x09, 0x02, 0x60, 0x01, 0x7f, 0x00, 0x60,
        0x00, 0x01, 0x7f,
        // func sec: 2 funcs : t0, t1
        0x03, 0x03, 0x02, 0x00, 0x01,
        // global mut i32 = 0
        0x06, 0x06, 0x01, 0x7f, 0x01, 0x41, 0x00, 0x0b,
        // export sec: "set" func0, "get" func1
        0x07, 0x0d, 0x02, 0x03, 0x73, 0x65, 0x74, 0x00,
        0x00, 0x03, 0x67, 0x65, 0x74, 0x00, 0x01,
        // code sec: 2 bodies
        0x0a,
        0x0d, 0x02,
        0x06, 0x00, 0x20, 0x00, 0x24, 0x00, 0x0b, // set: local.get 0; global.set 0
        0x04, 0x00, 0x23, 0x00, 0x0b, // get: global.get 0
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, null), try inst.invoke(testing.allocator, "set", &.{77}));
    try testing.expectEqual(@as(?u64, 77), try inst.invoke(testing.allocator, "get", &.{}));
}

test "JitInstance.invoke: mem64 OOB i32.load traps (D-234 corpus-path repro)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (memory i64 1) (func (export "i32.load") (param $a i64) (result i32)
    //   (i32.load (local.get $a))))  — invoke "i32.load" with 0x10000 (OOB) → must trap.
    // This is the EXACT corpus path (JitInstance.invoke on a kept instance) where
    // the 51 memory64 assert_trap fails live; the fresh-setupRuntime siblings trap
    // fine. If this RETURNS instead of trapping, D-234 is reproduced in the JIT
    // path; if it TRAPS, the corpus issue is in the runner's per-assert reuse.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7e, 0x01, 0x7f, // type (i64)->i32
        0x03, 0x02, 0x01, 0x00, // func
        0x05, 0x03, 0x01, 0x04, 0x01, // memory i64 1
        // export "i32.load" (8 bytes) func 0
        0x07, 0x0c, 0x01, 0x08, 0x69,
        0x33, 0x32, 0x2e, 0x6c, 0x6f,
        0x61, 0x64, 0x00, 0x00,
        // code: local.get 0; i32.load; end
        0x0a,
        0x09, 0x01, 0x07, 0x00, 0x20,
        0x00, 0x28, 0x02, 0x00, 0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    // The corpus invokes a trap-func MANY times on the same kept instance. A JIT
    // trap must leave the instance re-invokable (trap_flag reset). Three OOB
    // invokes must ALL trap; a non-trap on the 2nd/3rd = the D-234 root cause.
    try testing.expectError(error.Trap, inst.invoke(testing.allocator, "i32.load", &.{0x10000}));
    try testing.expectError(error.Trap, inst.invoke(testing.allocator, "i32.load", &.{0x10000}));
    try testing.expectError(error.Trap, inst.invoke(testing.allocator, "i32.load", &.{0x10000}));
    // The corpus runs IN-BOUNDS asserts before the OOB traps on the same instance.
    _ = try inst.invoke(testing.allocator, "i32.load", &.{0}); // in-bounds
    try testing.expectError(error.Trap, inst.invoke(testing.allocator, "i32.load", &.{0x10000})); // OOB after in-bounds
}

// ── ADR-0128 §1 / D-215: real JIT memory.grow (realloc + persist + max) ──

test "JitInstance: memory.grow grows + persists, memory.size reflects it" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (memory 0)
    //   (func (export "g") (param i32) (result i32) local.get 0 memory.grow)
    //   (func (export "s") (result i32) memory.size))
    // Default memory_grow_fn rejected (returned -1); a real one grows the
    // realloc'd buffer and updates rt.vm_base/mem_limit so size persists.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x0a, 0x02, 0x60, 0x01, 0x7f, 0x01, 0x7f,
        0x60, 0x00, 0x01, 0x7f, 0x03, 0x03, 0x02, 0x00,
        0x01,
        0x05, 0x03, 0x01, 0x00, 0x00, // memory: min 0, no max
        0x07, 0x09, 0x02, 0x01, 0x67, 0x00, 0x00, 0x01, 0x73, 0x00, 0x01, // exports g,s
        0x0a, 0x0d, 0x02,
        0x06, 0x00, 0x20, 0x00, 0x40, 0x00, 0x0b, // g: local.get 0; memory.grow 0
        0x04, 0x00, 0x3f, 0x00, 0x0b, // s: memory.size 0
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 0), try inst.invoke(testing.allocator, "s", &.{})); // size 0
    try testing.expectEqual(@as(?u64, 0), try inst.invoke(testing.allocator, "g", &.{1})); // grow→old 0
    try testing.expectEqual(@as(?u64, 1), try inst.invoke(testing.allocator, "s", &.{})); // size 1 (persisted)
    try testing.expectEqual(@as(?u64, 1), try inst.invoke(testing.allocator, "g", &.{1})); // grow→old 1
    try testing.expectEqual(@as(?u64, 2), try inst.invoke(testing.allocator, "s", &.{})); // size 2
}

test "JitInstance: memory.grow past declared max returns -1" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (memory 0 1) (func (export "g") (param i32) (result i32) local.get 0 memory.grow))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7f, 0x01, 0x7f,
        0x03, 0x02, 0x01, 0x00,
        0x05, 0x04, 0x01, 0x01, 0x00, 0x01, // memory: flag=has_max, min 0, max 1
        0x07, 0x05, 0x01, 0x01, 0x67, 0x00,
        0x00, 0x0a, 0x08, 0x01, 0x06, 0x00,
        0x20, 0x00, 0x40, 0x00, 0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 0), try inst.invoke(testing.allocator, "g", &.{1})); // 0→1 ok, old 0
    // grow by 1 more → 2 > max 1 → -1 (i32 -1 = 0xffffffff zero-extended in the carrier)
    try testing.expectEqual(@as(?u64, 0xffffffff), try inst.invoke(testing.allocator, "g", &.{1}));
}

// ── ADR-0128 §1 / D-216 Part B: memory64 grow -1 result i64 sign-extension ──

test "JitInstance: memory64 grow past max returns i64 -1 (sign-extended, not 0x0000_0000ffffffff)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (memory i64 0 1)
    //   (func (export "g") (param i64) (result i64) local.get 0 memory.grow))
    // memory64 grow result is i64; the -1 failure sentinel must widen to a
    // full i64 -1 (0xffff_ffff_ffff_ffff), not the i32 -1 zero-extended to
    // 0x0000_0000_ffff_ffff that the pre-D-216 zero-ext capture produced.
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x01, 0x60, 0x01, 0x7e, 0x01, 0x7e, // type (i64)->(i64)
        0x03, 0x02, 0x01, 0x00,
        0x05, 0x04, 0x01, 0x05, 0x00, 0x01, // memory: flag=mem64|has_max, min 0, max 1
        0x07, 0x05, 0x01, 0x01, 0x67, 0x00,
        0x00, 0x0a, 0x08, 0x01, 0x06, 0x00,
        0x20, 0x00, 0x40, 0x00, 0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 0), try inst.invoke(testing.allocator, "g", &.{1})); // 0→1 ok, old 0
    // grow → 2 > max 1 → i64 -1 = all-ones (the sign-extension under test)
    try testing.expectEqual(@as(?u64, 0xffffffffffffffff), try inst.invoke(testing.allocator, "g", &.{1}));
}

// ── ADR-0128 §1 / D-217: two-scalar-arg JIT dispatch ──

test "JitInstance: (i32,i32)->i32 add dispatches two args (3,4)->7" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "add") (param i32 i32) (result i32)
    //   local.get 0 local.get 1 i32.add))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x07, 0x01, 0x60, 0x02, 0x7f, 0x7f, 0x01, 0x7f, // type (i32,i32)->(i32)
        0x03, 0x02, 0x01, 0x00,
        0x07, 0x07, 0x01, 0x03, 0x61, 0x64, 0x64, 0x00, 0x00, // export "add"
        0x0a, 0x09, 0x01, 0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x6a, 0x0b, // local.get 0,1; i32.add
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 7), try inst.invoke(testing.allocator, "add", &.{ 3, 4 }));
}

test "JitInstance: (i64,i64)->i64 add dispatches two i64 args (10,20)->30" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "addq") (param i64 i64) (result i64)
    //   local.get 0 local.get 1 i64.add))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x07, 0x01, 0x60, 0x02, 0x7e, 0x7e, 0x01, 0x7e, // type (i64,i64)->(i64)
        0x03, 0x02, 0x01, 0x00,
        0x07, 0x08, 0x01, 0x04, 0x61, 0x64, 0x64, 0x71, 0x00, 0x00, // export "addq"
        0x0a, 0x09, 0x01, 0x07, 0x00, 0x20, 0x00, 0x20, 0x01, 0x7c, 0x0b, // local.get 0,1; i64.add
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 30), try inst.invoke(testing.allocator, "addq", &.{ 10, 20 }));
}

// ── ADR-0128 §1 / D-217: three-i32-arg JIT dispatch (corpus's only 3-arg shape) ──

test "JitInstance: (i32,i32,i32)->i32 sum dispatches three args (1,2,3)->6" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "f") (param i32 i32 i32) (result i32)
    //   local.get 0 local.get 1 i32.add local.get 2 i32.add))
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x08, 0x01, 0x60, 0x03, 0x7f, 0x7f, 0x7f, 0x01, 0x7f, // type (i32,i32,i32)->(i32)
        0x03, 0x02, 0x01, 0x00,
        0x07, 0x05, 0x01, 0x01, 0x66, 0x00, 0x00, // export "f"
        0x0a, 0x0c, 0x01, 0x0a, 0x00, 0x20, 0x00,
        0x20, 0x01, 0x6a, 0x20, 0x02, 0x6a, 0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 6), try inst.invoke(testing.allocator, "f", &.{ 1, 2, 3 }));
}

// ── ADR-0128 §1 / D-219: memory64 active-data offset is i64 (JIT compile gate) ──

test "JitInstance: memory64 module with active data at i64 offset compiles + loads" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (memory i64 1)
    //   (data (i64.const 0) "\2a\00\00\00")   ;; 42 at addr 0 (offset expr is i64!)
    //   (func (export "ld") (result i32) i64.const 0 i32.load))
    // The JIT compile gate validated active-data offset exprs against i32,
    // rejecting the memory64 i64.const offset with InvalidGlobalInitExpr (D-219).
    // (i32.load — supported on mem64 per D-181; load8/16 are a separate gap.)
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x05, 0x01, 0x60, 0x00, 0x01, 0x7f, // type ()->(i32)
        0x03, 0x02, 0x01, 0x00,
        0x05, 0x03, 0x01, 0x04, 0x01, // memory: flag=0x04 (i64), min 1
        0x07, 0x06, 0x01, 0x02, 0x6c, 0x64, 0x00, 0x00, // export "ld"
        0x0a, 0x09, 0x01, 0x07, 0x00, 0x42, 0x00, 0x28, 0x02, 0x00, 0x0b, // i64.const 0; i32.load align=2 off=0
        // data sec: 1 active seg, memidx 0, offset (i64.const 0), bytes "\2a\00\00\00"
        0x0b, 0x0a, 0x01, 0x00, 0x42, 0x00, 0x0b, 0x04, 0x2a, 0x00, 0x00,
        0x00,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    try testing.expectEqual(@as(?u64, 42), try inst.invoke(testing.allocator, "ld", &.{}));
}

test "JitInstance.invokeMulti: 2-result (i32 i32) returns both values via entry_buf (ADR-0106 cycle 3 — multi-value JIT corpus)" {
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "pair") (result i32 i32) i32.const 7 i32.const 9))
    // The single-result `invoke` rejects results.len>1; multi-value
    // reuses the ADR-0106 wrapper-thunk buffer-write entry (entry_buf).
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // \0asm + version
        // type sec: 1 type, () -> (i32 i32)
        0x01, 0x06, 0x01, 0x60, 0x00, 0x02, 0x7f, 0x7f,
        // func sec: 1 func, type 0
        0x03, 0x02, 0x01, 0x00,
        // export sec: 1 export, name="pair", kind=func, idx=0
        0x07, 0x08, 0x01, 0x04,
        0x70, 0x61, 0x69, 0x72, 0x00, 0x00,
        // code sec: 1 body, size 6: locals=0, i32.const 7, i32.const 9, end
        0x0a, 0x08,
        0x01, 0x06, 0x00, 0x41, 0x07, 0x41, 0x09, 0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    var results = [_]TypedResult{ undefined, undefined };
    try inst.invokeMulti(testing.allocator, "pair", &.{}, &results);
    try testing.expectEqual(@as(u32, 7), results[0].i32);
    try testing.expectEqual(@as(u32, 9), results[1].i32);
}

test "JitInstance.invokeMulti: 1-param 2-result returns (arg, 42) — arm64 param-bearing wrapper thunk" {
    // arm64-only: the param-bearing multi-value wrapper thunk is emitted by
    // `emitAarch64` (AAPCS). The x86_64 SysV path still rejects params (NO_THUNK
    // → invokeMulti skips), so this shape is unsupported there (D-229). Mirrors
    // the existing per-arch byte tests' gating.
    // SIBLING-AT: src/engine/codegen/shared/wrapper_thunk.zig (x86_64 SysV param-bearing thunk: D-229)
    if (comptime builtin.cpu.arch != .aarch64) return;
    if (builtin.os.tag == .windows) return skip.phaseEnd(.win64);
    // (module (func (export "swap") (param i32) (result i32 i32)
    //   (local.get 0) (i32.const 42)))
    // Exercises the param-bearing wrapper thunk: param0 loaded from the
    // buffer-write args ptr into the body's X1 (AAPCS), results in X0/X1.
    // (const 42 = 0x2a, single-byte SLEB128 positive; 0x64 would be -28.)
    const bytes = [_]u8{
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, // \0asm + version
        // type sec: 1 type, (i32) -> (i32 i32)
        0x01, 0x07, 0x01, 0x60, 0x01, 0x7f, 0x02, 0x7f,
        0x7f,
        // func sec: 1 func, type 0
        0x03, 0x02, 0x01, 0x00,
        // export sec: 1 export, name="swap", kind=func, idx=0
        0x07, 0x08, 0x01,
        0x04, 0x73, 0x77, 0x61, 0x70, 0x00, 0x00,
        // code sec: 1 body, size 6: locals=0, local.get 0, i32.const 42, end
        0x0a,
        0x08, 0x01, 0x06, 0x00, 0x20, 0x00, 0x41, 0x2a,
        0x0b,
    };
    var inst = try JitInstance.init(testing.allocator, &bytes);
    defer inst.deinit(testing.allocator);
    var results = [_]TypedResult{ undefined, undefined };
    try inst.invokeMulti(testing.allocator, "swap", &.{5}, &results);
    try testing.expectEqual(@as(u32, 5), results[0].i32);
    try testing.expectEqual(@as(u32, 42), results[1].i32);
}
